print("Hello World")
print("Somehow it Works")
print("Learnt using git through terminal for version control")
print("Summary of commands to run python file added to README")
print("added learnind-data-science repo to wajihh")